CREATE OR REPLACE FUNCTION VALIDATE_CNPJ(CNPJ VARCHAR(14))
RETURNS INTEGER AS $$
    DECLARE DIG1 INTEGER := 0;
    DECLARE DIG2 INTEGER := 0;
    DECLARE RESULT INTEGER := 0;
BEGIN
    DIG1 := DIG1 + 5 * CAST(SUBSTRING(CNPJ,1,1) AS INTEGER);
    DIG1 := DIG1 + 4 * CAST(SUBSTRING(CNPJ,2,1) AS INTEGER);
    DIG1 := DIG1 + 3 * CAST(SUBSTRING(CNPJ,3,1) AS INTEGER);
    DIG1 := DIG1 + 2 * CAST(SUBSTRING(CNPJ,4,1) AS INTEGER);

    DIG1 := DIG1 + 9 * CAST(SUBSTRING(CNPJ,5,1) AS INTEGER);
    DIG1 := DIG1 + 8 * CAST(SUBSTRING(CNPJ,6,1) AS INTEGER);
    DIG1 := DIG1 + 7 * CAST(SUBSTRING(CNPJ,7,1) AS INTEGER);
    DIG1 := DIG1 + 6 * CAST(SUBSTRING(CNPJ,8,1) AS INTEGER);

    DIG1 := DIG1 + 5 * CAST(SUBSTRING(CNPJ,9,1) AS INTEGER);
    DIG1 := DIG1 + 4 * CAST(SUBSTRING(CNPJ,10,1) AS INTEGER);
    DIG1 := DIG1 + 3 * CAST(SUBSTRING(CNPJ,11,1) AS INTEGER);
    DIG1 := DIG1 + 2 * CAST(SUBSTRING(CNPJ,12,1) AS INTEGER);
    DIG1 := 11 - (DIG1 % 11);
    IF DIG1 >= 10 THEN
        DIG1 := 0;
    END IF;

    DIG2 := DIG2 + 6 * CAST(SUBSTRING(CNPJ,1,1) AS INTEGER);
    DIG2 := DIG2 + 5 * CAST(SUBSTRING(CNPJ,2,1) AS INTEGER);
    DIG2 := DIG2 + 4 * CAST(SUBSTRING(CNPJ,3,1) AS INTEGER);
    DIG2 := DIG2 + 3 * CAST(SUBSTRING(CNPJ,4,1) AS INTEGER);

    DIG2 := DIG2 + 2 * CAST(SUBSTRING(CNPJ,5,1) AS INTEGER);
    DIG2 := DIG2 + 9 * CAST(SUBSTRING(CNPJ,6,1) AS INTEGER);
    DIG2 := DIG2 + 8 * CAST(SUBSTRING(CNPJ,7,1) AS INTEGER);
    DIG2 := DIG2 + 7 * CAST(SUBSTRING(CNPJ,8,1) AS INTEGER);

    DIG2 := DIG2 + 6 * CAST(SUBSTRING(CNPJ,9,1) AS INTEGER);
    DIG2 := DIG2 + 5 * CAST(SUBSTRING(CNPJ,10,1) AS INTEGER);
    DIG2 := DIG2 + 4 * CAST(SUBSTRING(CNPJ,11,1) AS INTEGER);
    DIG2 := DIG2 + 3 * CAST(SUBSTRING(CNPJ,12,1) AS INTEGER);
    DIG2 := DIG2 + 2 * CAST(SUBSTRING(CNPJ,13,1) AS INTEGER);
    DIG2 := 11 - (DIG2 % 11);
    IF DIG2 >= 10 THEN
        DIG2 := 0;
    END IF;

    IF DIG1 = CAST(SUBSTRING(CNPJ,13,1) AS INTEGER) AND
       DIG2 = CAST(SUBSTRING(CNPJ,14,1) AS INTEGER)
    THEN
        RESULT := 1;
    ELSE
        RESULT := 0;
    END IF;

    RETURN RESULT;
END;
$$ LANGUAGE PLPGSQL;


SELECT VALIDATE_CNPJ('23610773000195');
SELECT VALIDATE_CNPJ('11111111111111');
DROP FUNCTION VALIDATE_CNPJ;